
package com.m104.futebol.model.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnviaTimeService", targetNamespace = "http://webservice.model.futebol.m104.com/", wsdlLocation = "http://localhost:8085/futebol/EnviaTime?wsdl")
public class EnviaTimeService
    extends Service
{

    private final static URL ENVIATIMESERVICE_WSDL_LOCATION;
    private final static WebServiceException ENVIATIMESERVICE_EXCEPTION;
    private final static QName ENVIATIMESERVICE_QNAME = new QName("http://webservice.model.futebol.m104.com/", "EnviaTimeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/futebol/EnviaTime?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENVIATIMESERVICE_WSDL_LOCATION = url;
        ENVIATIMESERVICE_EXCEPTION = e;
    }

    public EnviaTimeService() {
        super(__getWsdlLocation(), ENVIATIMESERVICE_QNAME);
    }

    public EnviaTimeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENVIATIMESERVICE_QNAME, features);
    }

    public EnviaTimeService(URL wsdlLocation) {
        super(wsdlLocation, ENVIATIMESERVICE_QNAME);
    }

    public EnviaTimeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENVIATIMESERVICE_QNAME, features);
    }

    public EnviaTimeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnviaTimeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnviaTime
     */
    @WebEndpoint(name = "EnviaTimePort")
    public EnviaTime getEnviaTimePort() {
        return super.getPort(new QName("http://webservice.model.futebol.m104.com/", "EnviaTimePort"), EnviaTime.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnviaTime
     */
    @WebEndpoint(name = "EnviaTimePort")
    public EnviaTime getEnviaTimePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.model.futebol.m104.com/", "EnviaTimePort"), EnviaTime.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENVIATIMESERVICE_EXCEPTION!= null) {
            throw ENVIATIMESERVICE_EXCEPTION;
        }
        return ENVIATIMESERVICE_WSDL_LOCATION;
    }

}
